### ISSUE TITLE
Duplicate data after updating to version 1.3.0

### ISSUE THREAD

**Issue by DonBrowny** [probberechts/soccerdata#114]
After updating from version 1.2.0 to 1.3.0 data from the fbref is repeated twice 
The sample code
```
fb_data = fbref.read_player_match_stats(
                stat_type='summary', match_id=None, force_cache=False)
            fb_data.to_csv('./summary.csv')
```
log from version 1.3.0
<img width="838" alt="image" src="https://user-images.githubusercontent.com/17572565/204137821-46ab4c6d-59d5-4864-912c-dd18ffe293eb.png">

log from version 1.2.0
<img width="820" alt="image" src="https://user-images.githubusercontent.com/17572565/204137879-6c1ccf90-0fbd-4190-895b-d4d35ffdc67d.png">

In version 1.3.0, the log Retrieving game with id=**** is repeating twice.

**Comment by probberechts** [comment]
I cannot reproduce this. Also, it cannot be related to the v1.3 update as this part of the code was not modified. Which league/season are you attempting to scrape?

**Comment by DonBrowny** [comment]
I am trying to scrape `ENG-Premier League`

**Comment by probberechts** [comment]
This seems to work fine on my end. I'll reopen if you can provide additional details about what causes the problem on your end.
