### ISSUE TITLE
FBRef pulling back "out of date" statistics

### ISSUE THREAD

**Issue by philbywalsh** [probberechts/soccerdata#124]
When using the API to scrape from FBRef I noticed something odd.

The APIs for each category of stats (e.g. shooting, passing) don't seem to be working off the same baseline of minutes played.

For example: take Emiliano Martínez (Argentina). The "90s" value should be consistent across each of these categories - but across the 5 categories below it varies extensively.

fbref.read_player_season_stats(stat_type="standard") = 2.0
fbref.read_player_season_stats(stat_type="shooting") = 2.0
fbref.read_player_season_stats(stat_type="goal_shot_creation") = 3.0
fbref.read_player_season_stats(stat_type="passing") = 3.0
fbref.read_player_season_stats(stat_type="defense") = 5.3

Note: This didn't seem to be an issue earlier in the tournament. Also, I only recently scraped "defense" statistics for the first time, so I wonder if somehow the results of old queries are being cached?

Also, when I navigate to the specific pages in by browser the data looks to be consistent & fully up to-date (i.e. a value of 6.3 for the "90s" attribute for Emiliano Martínez)

https://fbref.com/en/comps/1/passing/World-Cup-Stats

**Comment by probberechts** [comment]
Yes, all data is cached by default. To pull up-to-date data you should use `socerdata.FBref(no_cache=True)`. To disable caching you can use `socerdata.FBref(no_store=True)`.

**Comment by philbywalsh** [comment]
Ah yes, much appreciated!
