### ISSUE TITLE
[WhoScored] Scrapping does not include second

### ISSUE THREAD

**Issue by BenSarfatiDS** [probberechts/soccerdata#141]
Hello, 

Thanks for the package, it is really useful and well coded. And thanks for the quick fix (regarding missing is_goal or is_card columns).

I have one question regarding the available columns in the returned dataframe: 

**Is there any reason the 'second' column is not kept ?** 
The information is available in json_data but then not included in the final dataframe. Regarding the last commit you made, it could be added in the COLS_EVENTS list, in [line 42 ](https://github.com/probberechts/soccerdata/blob/cbde3791f21504366e5ca472798d059508fce129/soccerdata/whoscored.py#L42) : 

"#" Integer indicating the second of the event, ignoring stoppage time
"second": -1,

There are maybe reasons for this to be omit from the returned dataframe, but if not, I guess it could be useful for different use cases. 

Thanks again, 
Ben

**Comment by probberechts** [comment]
No, there is no particular reason for ignoring it. I think I just overlooked it. I'll add it now.

**Comment by BenSarfatiDS** [comment]
Thank you for the quick answer
