### ISSUE TITLE
Remove flake8-plugins from normal dependencies

### ISSUE THREAD

**Issue by JeremieSiller** [probberechts/soccerdata#150]
These dependencies are currently stored in `[tool.poetry.dependencies]` and `[tool.poetry.dev-dependencies]`:
```
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.3.0"
```
They are only needed for development, so they should not be in `[tool.poetry.dependencies]`.

**Comment by probberechts** [comment]
Good catch! Thanks.

**Comment by JeremieSiller** [comment]
Thanks for the quick fix, but
after pulling the changes, I get this error when installing: 
```
Because soccerdata depends on flake8 (^6.0.0) which doesn't match any versions, version solving failed.
```
After deleting the `poetry.lock` file, it was fine so, you might need to delete the `poetry.lock` file.

**Comment by probberechts** [comment]
Indeed. I did not think about that.
