### ISSUE TITLE
Incorporating Understat as a Data Source

### ISSUE THREAD

**Issue by Kalaweksh** [probberechts/soccerdata#151]
[Understat](https://understat.com/) exposes data, current and historical, without any apparent restrictions on usage (i.e lacking a robots.txt) on the big 5. It has detailed data on both the player and club level, and even an [unofficial API](https://github.com/amosbastian/understat) that could perhaps be integrated as a data source.

**Comment by lorenzodb1** [comment]
Are there any stats you could get from understat that you couldn't get from FBref (besides the difference in the xG model used)?

**Comment by Kalaweksh** [comment]
> Are there any stats you could get from understat that you couldn't get from FBref (besides the difference in the xG model used)?

I believe xGChain and xGBuildup, for players at least. Although I think those could be calculated from the stats FBref exposes. 

There are a few more alternative stats for teams, such as a team's tempo (what is Dortmund's xG on a slow attack as opposed to their xG for a fast attack) and shot zones.

Understat is also much faster to scrape and allows users to scrape between arbitrary dates, avoiding unnecessary scraping.
