### ISSUE TITLE
[WhoScored] The current season's schedule is not cached

### ISSUE THREAD

**Issue by guilherme-95** [probberechts/soccerdata#169]
I'm facing the following issue when trying to scrape game data for the 22-23 season - when I ask ws.read_events to return data from a list of game IDs in the 21-22 season, it will scrape the schedule once and move on to getting the game data. If I do it for the 22-23 season, it starts scraping the schedule for every game_id I want data from.

It doesn't matter if I point to the schedule file in /soccerdata/data/WhoScored/matches or if I build a new file using ws.read_schedule 

The code I'm running is below:

```python
import pandas as pd
import soccerdata as sd

ws = sd.WhoScored(leagues="ENG-Premier League", seasons="22-23")

match_ids_df = pd.read_csv("premier_league_schedule.csv")

events = ws.read_events(match_id=match_id)
events = events.fillna(0)

filename = f"match_data_{match_id}.csv"
events.to_csv(filename, index=False)
```

I apologize if this is an error on my end, I'm not very experienced with python.

**Comment by probberechts** [comment]
This is supposed to be a feature. By default, the scraper assumes that the cache is outdated for the current season. If you are sure that the cache is up to date, you can force the scraper to use the cache by setting the `force_cache` parameter to true.

```python
import soccerdata as sd

ws = sd.WhoScored(leagues="ENG-Premier League", seasons="22-23")
events = ws.read_events(match_id=..., force_cache=True)
```

**Comment by guilherme-95** [comment]
thank you very much for the information

**Comment by guilherme-95** [comment]
Sorry, forgot to close the issue.
