### ISSUE TITLE
Incorporating Fotmob as a data source

### ISSUE THREAD

**Issue by marcjbaron** [probberechts/soccerdata#170]
[Fotmob](https://www.fotmob.com/) could be useful as a potential data source; it contains advanced statistics of many lower leagues that are not covered by the already included data sources. They also have an accessible API for accessing the statistics. I have started working on away to incorporate this into the existing soccerdata framework (as a personal project, if nothing else).

**Comment by probberechts** [comment]
Feel free to create a pull request if you have a working implementation. I agree that it would be an interesting data source to add.

**Comment by TK5-Tim** [comment]
I have quite a few functions for fotmob in a script and would be happy to help set this up!
