### ISSUE TITLE
[SoFIFA] Scraper gets blocked by bot protection service

### ISSUE THREAD

**Issue by andrzej-konczyk** [probberechts/soccerdata#219]
Hi! How can I set up rpxy to get data? I would like to use read_players() function, but there is issue with download data. I am not sure how to set up properly proxy, I assume that can be issue. Current Error is ConnectionError: Could not download https://sofifa.com/.

**Comment by probberechts** [comment]
It looks like SoFifa has installed stronger protection against scraping through CloudFlare. Setting up a proxy will not help. I do not have a quick solution for this. Probably we will have to keep track of some cookies and add them to the request header or switch to a Selenium-based scraper to bypass the block.

**Comment by probberechts** [comment]
Based on some limited initial tests, it seems to work with [cfscrape](https://github.com/Anorov/cloudflare-scrape).

```py
# Using requests fails
>>> import requests
>>> requests.get("https://sofifa.com/")
>>> <Response [403]>

# Using cfscrape works
>>> import cfscrape
>>> scraper = cfscrape.create_scraper()
>>> scraper.get("https://sofifa.com/")
>>> <Response [200]>

# However, it fails when a session is used
>>> session = requests.Session()
>>> scraper = cfscrape.create_scraper(sess=session)
>>> scraper.get("https://sofifa.com/")
>>> <Response [403]>
```
