### ISSUE TITLE
[FBref] fbref.read_schedule() error on MLS

### ISSUE THREAD

**Issue by Innursery** [probberechts/soccerdata#246]
the fbref.read_schedule() gives error on MLS champion chip.
` [m[1;30m-------------------------------------------------------------------------------[m
[m[1;36mrun.py [1;32m578 [1;34mruncode
[m[1;37mexec(code, self.locals)
[m
[m[1;36mtest 4.py [1;32m42 [1;34m<module>
[m[1;37mepl_schedule = fbref.read_schedule()
[m
[m[1;36mfbref.py [1;32m493 [1;34mread_schedule
[m[1;37mdf_table["Match Report"] = [
[m
[m[1;36mframe.py [1;32m3980 [1;34m__setitem__
[m[1;37mself._set_item(key, value)
[m
[m[1;36mframe.py [1;32m4174 [1;34m_set_item
[m[1;37mvalue = self._sanitize_column(value)
[m
[m[1;36mframe.py [1;32m4915 [1;34m_sanitize_column
[m[1;37mcom.require_length_match(value, self.index)
[m
[m[1;36mcommon.py [1;32m571 [1;34mrequire_length_match
[m[1;37mraise ValueError(
[m
[m[1;31mValueError:
[1;33mLength of values (493) does not match length of index (512)
[m`
Any idea what can cause this issue ?
Seems working fine with European league.

**Comment by probberechts** [comment]
I'll close this issue since the MLS is not supported. Nevertheless, feel free to continue the discussion on how to resolve this. Please also clean up your error log.
