### ISSUE TITLE
"qualifiers" and "satisfiedEventsTypes" definition list for whoscored data

### ISSUE THREAD

**Issue by randomcrit2020** [probberechts/soccerdata#259]
Is there a list of definitions of "qualifiers" and "satisfiedEventsTypes" for the whoscored data ? for example, I'm trying to know what does the following list means.

"satisfiedEventsTypes": [
91,
212,
36,
37,
217
],

**Comment by probberechts** [comment]
Here is a list with qualifiers: https://github.com/tomh05/football-scores/blob/master/data/reference/opta-qualifiers.json
I am not entirely sure what the "satisfiedEventTypes" are, but I believe they are used to tag events with subcategories such as "blocked shot", "shot off target", ... I believe you can infer the same from a combination of the action type, action result, and qualifiers. I've never used the "satisfiedEventTypes" attribute.

**Comment by randomcrit2020** [comment]
I found https://github.com/jokecamp/FootballData/blob/7865378fe97d8ed973c7e6b0dbcf8384b150cabe/random_docs/Opta%20Playground-%20F24%20documentation.docx and https://github.com/jokecamp/FootballData/blob/7865378fe97d8ed973c7e6b0dbcf8384b150cabe/random_docs/Opta-f24_appendices.docx but I wonder if there is anything newer.
