### ISSUE TITLE
Date format bug when scraping MatchHistory data

### ISSUE THREAD

**Issue by francescozonaro** [probberechts/soccerdata#260]
While trying to scrape some historical data from the past season, I noticed the dates were weird and the number of matches wasn't maxed as it should at the end of the season. After some research, matches that should have been played (for example) 01 September 2022 were identified as 09 January 2022 by the read_games() function.

Simply adding dayfirst=True when reading the date 

`.assign(date=lambda x: pd.to_datetime(x["date"] + ' ' + x['time'], dayfirst=True))` **line 106**

solved the issue for me.

The following was my call (from the docs)

```
mh = sd.MatchHistory(leagues="ITA-Serie A", seasons=2223)

hist = mh.read_games()
```

**Comment by probberechts** [comment]
Obviously 🤦‍♂️
Thanks for checking. Now it should work.

**Comment by francescozonaro** [comment]
Sure thing, thank you for your work!
