### ISSUE TITLE
Add FIFA Women's World Cup whoscored data

### ISSUE THREAD

**Issue by clairesecehDS** [probberechts/soccerdata#299]
Is it possible to add FIFA Women's World Cup to validated scraping league?

**Comment by probberechts** [comment]
I have not fully tested it yet, but it seems straightforward to add support for scraping the FIFA Women's World Cup data from FBref and WhoScored. I'll add it to the default supported leagues and make sure everything works tomorrow or during the weekend. If you would like to use it already, you should add the following to the `SOCCERDATA_DIR/config/league_dict.json` file:

```json
"INT-Women's World Cup": {
    "FBref": "FIFA Women's World Cup",
    "WhoScored": "International - FIFA Women's World Cup",
}
```

Next, you should be able to scrape the data with:
```python
import soccerdata as sd

ws = sd.WhoScored("INT-Women's World Cup", 2023, no_cache=True)
df_events = ws.read_events(match_id=1751717)

fbref = sd.FBref("INT-Women's World Cup", 2324, no_cache=True)
df_team_season_stats = fbref.read_team_season_stats()
```

**Comment by clairesecehDS** [comment]
That's worked fine. Thanks for your time!
