### ISSUE TITLE
[SoFIFA] read_league error

### ISSUE THREAD

**Issue by cobrabetting** [probberechts/soccerdata#317]
<img width="925" alt="Screenshot 2023-07-30 231351" src="https://github.com/probberechts/soccerdata/assets/121590622/1aa027ce-64e4-4621-9148-38038d18278d">

Hallo Pieter!

I get this keyError when trying to run the basic set up for sofifa team ratings. 
Any idea how to fix this? 

Many thanks in advance

**Comment by probberechts** [comment]
Thanks for flagging this! It should be fixed in the master branch. You can install it with
```
pip install -i https://test.pypi.org/simple/ soccerdata
```
