### ISSUE TITLE
[WhoScored] Errors in event data

### ISSUE THREAD

**Issue by ksbharaj** [probberechts/soccerdata#332]
HI all,

I have been scraping EPL data from recent seasons to run some models on, but I've spotted quite a few errors in event data scraped from WhoScored. One common one is registering a cross/pass as a dribble and assigning it to the wrong player. Take this example from Fulham vs Arsenal on 12th March 2023 (screenshot attached). Trossard provided a cross to Martinelli, who scored a header. However, WhoScored registered it as a failed cross, and as a dribble into the box by Martinelli from where Trossard actually crossed it. I have seen several of these, so happy to share more. **Curious to know if anyone has spotted this, and found a solution?**

I have also spotted some dribbles not registered (again, Martinelli's 80m solo goal vs Chelsea in Jan 2020 is instead registered as an 80m clearance by Mustafi!). 

![image](https://github.com/probberechts/soccerdata/assets/34198137/5b7e1a41-c3dd-4244-acd4-d6db41793160)

**Comment by probberechts** [comment]
Event stream data is primarily collected manually. Therefore, there will always be some errors in the data. Particularly in live data, the urgency of real-time constraints contributes to more inaccuracies. While data providers engage in post-game processing to rectify these errors, I'm uncertain whether WhoScored updates the data post-game.

It's important to note that event stream data isn't commonly employed for analyzing individual actions; rather, it is used for creating aggregated metrics across multiple matches. Consequently, the presence of a few errors within the data doesn't typically have a significant impact on the analysis, as these discrepancies tend to balance each other out.

If you need superior data quality, you'll have to pay for the data. StatsBomb stands out for its commitment to upholding data integrity. Opta also might have higher-quality (and more detailed) feeds than the ones provided on WhoScored. If you do not need up-to-date data, StatsBomb also provides a substantial amount of data free of charge at https://github.com/statsbomb/open-data.

To confirm, it appears you're working with the SPADL rendition of the data. Do these errors also appear in the raw event data? It's plausible that the errors might originate from issues within the SPADL conversion process.

**Comment by ksbharaj** [comment]
Hi-Thank you for your response! Your explanation helps me make sense of it all.
In the example provided, the errors don't really appear in the raw event data. The main issue seems to be that the raw event data does not have any "carry" data (as Statsbomb defines it). The conversion to SPADL seems to stitch on this carry/dribble data and does so erroneously for some edge cases. 

For the example provided, Trossard's cross is actually listed as "fail" in the event data because it takes a touch off Kenny Tete before landing on Martinelli's head. The SPADL conversion process seems to assume that Martinelli collected it from Tete's touch, dribbled toward the goal, and scored (image attached).

I have attached an Excel file that shows the raw event vs spadl data for a Martinelli goal for Arsenal vs Chelsea. As mentioned earlier, spadl registers it as an 80m clearance by Mustafi, followed immediately by a goal by Martinelli. However, the event data correctly shows a shorter clearance, and a recovery in his own half by Martinelli, and finally a goal a few seconds later.

Over the next few days, I can try to run this spadl conversion on Stasbomb open data to see if the same errors are seen. I'll get back to you on this.

[raw_vs_spadl_data.xlsx](https://github.com/probberechts/soccerdata/files/12397993/raw_vs_spadl_data.xlsx)

![image](https://github.com/probberechts/soccerdata/assets/34198137/e5fd6018-c6c8-47e2-8ee4-49cde581e921)

**Comment by probberechts** [comment]
These edge cases were resolved in https://github.com/ML-KULeuven/socceraction/pull/585. You should upgrade socceraction to v1.4.2 to get these fixes.

The SPADL representation of Trossard's cross now looks like this:
![deflection](https://github.com/probberechts/soccerdata/assets/2175271/d6225fc4-3c58-4301-8f1b-fde8873310a5)

The SPADL representation of Martinelli's goal now looks like this:
![recoveries](https://github.com/probberechts/soccerdata/assets/2175271/5532aa87-3da6-4388-964e-e751b4a68d31)

Thanks for flagging this!

**Comment by ksbharaj** [comment]
Thank you very much!
