### ISSUE TITLE
Versión borwser Chrome unable

### ISSUE THREAD

**Issue by javibp1980** [probberechts/soccerdata#340]
To day I have this error with scraper data. What I can do? Thanks. I can't download the older version of the browser

 ERROR                                                                                 _common.py:380
                                             The ChromeDriver was unable to initiate/spawn a new
                                             WebBrowser. You will not be able to scrape new data.
                                             Message: unknown error: cannot connect to chrome at
                             127.0.0.1:50825
                             from session not created: This version of ChromeDriver only supports Chrome
                             version 114
                             Current browser version is 116.0.5845.111
                             Stacktrace:
                             Backtrace:
                                     GetHandleVerifier [0x0084A813+48355]
                                     (No symbol) [0x007DC4B1]
                                     (No symbol) [0x006E5358]
                                     (No symbol) [0x007061AC]
                                     (No symbol) [0x007006B4]
                                     (No symbol) [0x00700491]
                                     (No symbol) [0x00730C55]
                                     (No symbol) [0x0073093C]
                                     (No symbol) [0x0072A536]
                                     (No symbol) [0x007082DC]
                                     (No symbol) [0x007093DD]
                                     GetHandleVerifier [0x00AAAABD+2539405]
                                     GetHandleVerifier [0x00AEA78F+2800735]
                                     GetHandleVerifier [0x00AE456C+2775612]
                                     GetHandleVerifier [0x008D51E0+616112]

**Comment by probberechts** [comment]
Try to upgrade undetected-chromedriver to the latest version (3.5.3). If that does not work, you might find some help in the [issues of the undetected-chromedriver repo](https://github.com/ultrafunkamsterdam/undetected-chromedriver).

**Comment by javibp1980** [comment]
upgrade undetected-chromedriver and selenium is running OK. Thanks
