### ISSUE TITLE
[socceraction] soccerdata 1.5.1 vs. socceraction 1.4.2 dependency conflicts 

### ISSUE THREAD

**Issue by ds-oliver** [probberechts/soccerdata#386]
### Please help, I'm desperate and about ready to simply give up. Been struggling with this package few weeks now. Thanks in advance.

> ❯ python3 /Users/hogan/soccerdata_sd/test-scrape.py
> ImportError: The socceraction package is required to use the 'spadl' or 'atomic-spadl' output format. Please install it with `pip install socceraction`.
> ❯ pip install socceraction
> soccerdata 1.5.1 requires pandas<3.0.0,>=2.0.0, but you have pandas 1.5.3 which is incompatible.
> ❯ pip install 'pandas>=2.0.0,<3.0.0'
> socceraction 1.4.2 requires pandas<2.0.0,>=1.3.3, but you have pandas 2.1.1 which is incompatible.

**Comment by probberechts** [comment]
SoccerAction v1.5.0 now has pandas 2.0 support.
