### ISSUE TITLE
[WhoScored] Blocked in headless mode

### ISSUE THREAD

**Issue by shufinskiy** [probberechts/soccerdata#395]
Hello.

I try get schedule EPL 2023-24 from whoscored.com with  
```python
import soccerdata as sd
ws = sd.Whoscored(leagues="ENG-Premier League", seasons=2023)
epl_schedule = ws.read_schedule()
```
With `headless=False` all work good, but `headless=True` code broken on call  `Whoscored._parse_season_stages()` method

![Снимок экрана от 2023-10-05 13-46-08](https://github.com/probberechts/soccerdata/assets/49508936/9440a6c8-04f3-4a4c-8548-54587a9345da)

I check `ws._driver.page_source` and get very strange html about blocking:

![Снимок экрана от 2023-10-05 13-47-59](https://github.com/probberechts/soccerdata/assets/49508936/98abcd8f-cc3e-4c75-8040-ab25d254fa46)

About 3 weeks ago everything was working fine

version package:
`soccerdata` 1.5.1
`selenium` 4.12.0
`undetected-chromedriver` 3.5.3
Chrome 117.0.5938.62
Ubuntu 18.04

**Comment by probberechts** [comment]
This will have to be fixed in [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues?q=is%3Aissue+is%3Aopen+headless).
