### ISSUE TITLE
[FBref] Incorrect data obtained from Team Season Stats

### ISSUE THREAD

**Issue by ksbharaj** [probberechts/soccerdata#424]
Hi,

I tried to run the following code to get the some team season stats for the EPL in 22-23:

fbref = sd.FBref(leagues="ENG-Premier League", seasons=["2223"], no_cache=True)
fbref.read_team_season_stats(stat_type='standard', no_cache=True)

However, the resulting data does not seem to be correct. For example, Arsenal's "Gls" value is 84, whereas they actually scored 88 in the entire season. All teams have such incorrect values, and I also see it when triggering the opposition_values to true. 

Does anyone have any idea what might be causing this issue?

**Comment by marvinl803** [comment]
Hey, I was looking into this issue and it seems like it is an issue with the FBref website itself. Soccerdata is correctly scraping all the results but it is the FBref website that has the inconsistency with the incorect values.
![fbref](https://github.com/probberechts/soccerdata/assets/27875562/84062413-6f70-446b-806a-2f7b9d3a005d)

**Comment by ksbharaj** [comment]
@marvinl803 Thank you for spotting this. I have sent the feedback to fbref. Hopefully they find the reason for the discrepancy, or rectify it
