### ISSUE TITLE
[SoFIFA] Error in setting up the scraper class

### ISSUE THREAD

**Issue by AZA-2003** [probberechts/soccerdata#449]
Hello, I have been getting this error whenever I set up the scraper for SoFIFA. Any idea as to what could be wrong ?
Thank you !

<img width="584" alt="image" src="https://github.com/probberechts/soccerdata/assets/76678524/cf91cd77-6efa-4ff3-8cd2-4e6d08ee7037">

**Comment by probberechts** [comment]
The HTML structure has been changed. You'll have to update the xpaths at line 146 and 154.

https://github.com/probberechts/soccerdata/blob/f64a29c704033b91c1ecd83cfe32a04b2bfa9d3d/soccerdata/sofifa.py#L146

https://github.com/probberechts/soccerdata/blob/f64a29c704033b91c1ecd83cfe32a04b2bfa9d3d/soccerdata/sofifa.py#L154

**Comment by AZA-2003** [comment]
Awesome ! Thank you so much sir !
