### ISSUE TITLE
FBRef seasons parameter does not work with read_player_season_stats method

### ISSUE THREAD

**Issue by Suwadith** [probberechts/soccerdata#46]
FBRef  read_player_season_stats method does not seems to be considering the seasons parameter. No matter what the season is mentioned inside the brackets it just retrevied the recent season player stats. 2021-2022. 

Code used is mentioned below

```
import soccerdata as sd

fbref = sd.FBref(no_cache=False, no_store=False, leagues="ENG-Premier League", seasons='11-12')
pl_player_season_stats = fbref.read_player_season_stats(stat_type='standard')
pl_player_season_stats .head()
```

Seasons parameter works perfectly with the read_team_season_stats method though.

**Comment by Suwadith** [comment]
Thanks for the update.
I still don't think this issue has been fixed.

I tried using the new 1.0.1 version, but the issue still prevails. 
Below in the screenshot you can see that some of these players should not exists in the 15-16 squad. 
It retrieves the data from the 2021-2022 season which is the most recent season ignoring the seasons parameter. 

```
import soccerdata as sd

fbref = sd.FBref(no_cache=False, no_store=False, leagues="ENG-Premier League", seasons=2015)

player_season_stats = fbref.read_player_season_stats(stat_type="standard")
player_season_stats.head()
```


![image_2022-05-31_014912361](https://user-images.githubusercontent.com/20539850/171072252-8dc048a9-d1e2-48af-a8f5-1429e6a409f4.png)

**Comment by probberechts** [comment]
Did you empty the cache? Try to set `no_cache=True` or remove the `~/soccerdata/data/FBref` directory.

Also make sure you are really running the updated version by running `print(sd.__version__)`.

**Comment by Suwadith** [comment]
> Did you empty the cache? Try to set `no_cache=True` or remove the `~/soccerdata/data/FBref` directory.
> 
> Also make sure you are really running the updated version by running `print(sd.__version__)`.

My bad. Thank you so much for pointing it out. 
It works perfectly :)
