### ISSUE TITLE
[WoScored] HTTPError: Not Found

### ISSUE THREAD

**Issue by kmicha03** [probberechts/soccerdata#485]
I've been using the soccerdata package to scrape the schedule for each league, it was working fine until today which I got this error while trying to read the first schedule:

```
whoscored_name = "ENG-Premier League"

ws = sd.WhoScored(leagues=whoscored_name, seasons=2324, headless=False)
```

The error occurs here inside the whoscored.py file:

```
"""Initialize the WhoScored reader."""
        super().__init__(
            leagues=leagues,
            proxy=proxy,
            no_cache=no_cache,
            no_store=no_store,
            data_dir=data_dir,
            path_to_browser=path_to_browser,
            headless=headless,
        )
        
```

Any ideas? Thank you!

**Comment by jbarrocal-str** [comment]
I have the same error. Please can someone help us?

**Comment by probberechts** [comment]
undetected-chromedriver needs to get updated.

`pip install --upgrade undetected-chromedriver`
