### ISSUE TITLE
[WhoScored] urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jbarrocal-str** [probberechts/soccerdata#491]
Hello, I need help. I have updated undetected-chromedriver and google chrome.

When I execute this code I have the error

>>>import soccerdata as sd
>>>import undetected_chromedriver as uc
>>>import json

>>>ws = sd.WhoScored(leagues="ESP-La Liga", seasons=2022)

 raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by probberechts** [comment]
I'll need more details. Which URL cannot be found? It would be helpful if you could provide the full stacktrace.

**Comment by jbarrocal-str** [comment]
Sorry, I have a error in upgrade undetected_chromedriver. Thank you!
