### ISSUE TITLE
Include Champions League to the FBRef data source.

### ISSUE THREAD

**Issue by luisgmfarias** [probberechts/soccerdata#500]
I would like to get information about Champions League and Europa League, how can I contribute?

**Comment by probberechts** [comment]
Are there any issues when you add it? See https://soccerdata.readthedocs.io/en/latest/howto/custom-leagues.html for instructions.

**Comment by luisgmfarias** [comment]
Not at all. Thanks for the instructions, I haven't seen it. Closing the issue.
