### ISSUE TITLE
JSON Files Not Populating

### ISSUE THREAD

**Issue by BentonNewman** [probberechts/soccerdata#513]
JSON files for teamname_replacements and league_dict are not populating. I uninstalled and reinstalled the package and it did not remedy the issue. Has anyone else encountered this? Any guidance or troubleshooting tips would be appreciated!

![Missing_JSONs](https://github.com/probberechts/soccerdata/assets/7414607/d7e4d9da-cadb-4a4f-b86b-d25c2917d90b)

**Comment by probberechts** [comment]
They are not created automatically if that is what you mean. You have to create them if you want to override team names or add additional leagues.
