### ISSUE TITLE
[WhoScored] Limit Scraping Schedule

### ISSUE THREAD

**Issue by LucasMo86** [probberechts/soccerdata#529]
Thank you for the work you put into this repository!

Is there a way to limit the scraping schedule by date?

For example I wanted to scrape all Premier League games since March but I couldn't find a way to stop it scraping the whole schedule back to the start of the season before scraping the games I wanted. 

Thanks again.

**Comment by probberechts** [comment]
No, this is not possible. I decided to scrape the full schedule again each time to ensure that postponed games are picked up.
