### ISSUE TITLE
[WhoScored] HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by thecourtchart** [probberechts/soccerdata#539]
A few months ago, I used the library to scrap WhoScore and everything ran smoothly. Then, after a long break, I decided to revisit and use the library again. Somehow, I got HTTPError: HTTP Error 404: Not Found after running the code:
`ws = sd.WhoScored(leagues="ITA-Serie A", seasons=2021)`

Does anyone have the same problem and how to fix it?

**Comment by probberechts** [comment]
Everything seems to work fine for me. I am just guessing, but this might be related to #485.

Make sure to update both soccerdata and undetected-chromedriver to the latest version. If you encounter any problems, it might also help to disable caching such that any outdated files are overridden: `ws = sd.WhoScored(leagues="ITA-Serie A", seasons=2021, no_cache=True)`.

If this does not fix it, it would be helpful if you could provide the URL for which the 404 error is raised (i.e., what is the full error)?

**Comment by thecourtchart** [comment]
Solved Perfectly!
