### ISSUE TITLE
[FBref] Error getting player1 in some events

### ISSUE THREAD

**Issue by nachouve** [probberechts/soccerdata#544]
**Issue Summary:**

I encountered an issue with soccerdata while parsing HTML for certain events in FBref.

**Details:**
The error occurs in [this line](https://github.com/nachouve/soccerdata/blob/149ecb6a456dc50e0b4f54833c78f6dc6ccc48e4/soccerdata/fbref.py#L987) of the code where the player1 variable is set. Sometimes, there is no <a> tag present here, but it has the name of person who was issued with a yellow card, for example.

**Steps to Reproduce:**

```python
import soccerdata as sd
fbref = sd.FBref(seasons=['2324'], leagues=["ESP-La Liga"])
fbref.read_events(match_id="e8867e6b")
```

**Expected Behavior:**
The read_events() function should handle cases where the <a> tag is missing gracefully, rather than causing an error.

**Comment by nachouve** [comment]
**Issue Update:**
It appears that the changes made in [this commit](https://github.com/nachouve/soccerdata/commit/e0d49f82cd78874544c7c946d239f8635cdb3581) address the reported problem.

**Request for Review:**
As I'm not familiar with some of the technologies used in the project, I would appreciate any guidance on potential improvements or corrections needed before merging the fix.

Thank you in advance for your assistance.

**Comment by probberechts** [comment]
I've added a suggestion on how to implement this a bit more cleaner. But functionally, your fix seems ok. Would you be able to create a pull request?

**Comment by nachouve** [comment]
> I've added a suggestion on how to implement this a bit more cleaner. But functionally, your fix seems ok. Would you be able to create a pull request?

Perfect. I'll do it. Thank you!
