### ISSUE TITLE
[Whoscored] Scraping Issue with EFL

### ISSUE THREAD

**Issue by WillT23** [probberechts/soccerdata#557]
Hi,

When running the loader to scrape for games in the English Championship & League One (possibly League Two as well), the loader when scraping the schedule looks like it is trying to find playoff games which don't exist yet. It then just keeps going back in the calendar on the website but never finds a game as there aren't any. Is this an issue that can be fixed or do we just have to wait until playoff fixtures are decided?

Thanks,

Will

**Comment by probberechts** [comment]
The English Championship & League One are not supported, hence I will not implement a fix. Maintaining compatibility with every possible league is not manageable for me. If you can fix it yourself and it does not break other functionality, feel free to create a pull request.

**Comment by joaomcalves** [comment]
@probberechts first of all thank you for the awesome work! 
Is there a list with the supported leagues?

**Comment by probberechts** [comment]
@joaomcalves The leagues available for each source can be listed with the [available_leagues()](https://soccerdata.readthedocs.io/en/latest/reference/fbref.html#soccerdata.FBref.available_leagues) class method. For example:
```python
sd.FBref.available_leagues()
>>> ['Big 5 European Leagues Combined', 'ENG-Premier League', 'ESP-La Liga', 'FRA-Ligue 1', 'GER-Bundesliga', 'ITA-Serie A', 'INT-World Cup', "INT-Women's World Cup"]
```

**Comment by joaomcalves** [comment]
Thanks @probberechts but for example I have been using the FBREF scrapper for the top5 second leagues, portuguese league, dutch league or belgian league.

Btw thank you very much for this project. It has been super important for me. I have started a twitter page (dadosdojogo) where I have been exploring using data to analyse teams and players and this project helped me a lot to get access to data. As you know data is a huge bottleneck when you are starting in this field.

**Comment by probberechts** [comment]
Yes, it might work out-of-the-box for other leagues apart from the ones in the `available_leagues` list, but if it is not in the list, I didn't test it and I do not provide support for it.
