### ISSUE TITLE
[WhoScored] Broken read_schedule() method

### ISSUE THREAD

**Issue by probberechts** [probberechts/soccerdata#581]
WhoScored has updated the HTML structure of their fixture pages. The scraper must be updated accordingly.

**Comment by ds-oliver** [comment]
Hey - are we getting WS scraper back up?

**Comment by probberechts** [comment]
I am working on it. You can already use the version in the `fix/whoscored-schedule` branch. I need to do a bit more testing before releasing it.

**Comment by ds-oliver** [comment]
> I am working on it. You can already use the version in the `fix/whoscored-schedule` branch. I need to do a bit more testing before releasing it.

I'll check that out. Cheers.

**Comment by ds-oliver** [comment]
> I am working on it. You can already use the version in the `fix/whoscored-schedule` branch. I need to do a bit more testing before releasing it.

I tried to follow your advice with this and have encountered an issue while trying to check out and install the `fix/whoscored-schedule` branch. Here are the steps I followed and the errors I encountered:

1. **Cloned the repository:**
   ```bash
   git clone https://github.com/probberechts/soccerdata.git soccerdata_whoscored_schedule
   cd soccerdata_whoscored_schedule
   ```

2. **Checked out the specific branch:**
   ```bash
   git fetch --all
   git checkout fix/whoscored-schedule
   ```

3. **Created and activated a virtual environment:**
   ```bash
   python -m venv venv
   source venv/bin/activate
   ```

4. **Upgraded pip, setuptools, and wheel:**
   ```bash
   pip install --upgrade pip setuptools wheel
   ```

5. **Attempted to install the package in editable mode:**
   ```bash
   pip install -e .
   ```

Despite these steps, I received the following error:
```
ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
```

I also tried creating a `pyproject.toml` file with the following content, but the issue persisted:
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

Additionally, I attempted to bypass the isolated build environment:
```bash
pip install --no-build-isolation -e .
```

However, the error still persists. Could you please provide guidance on how to resolve this issue? Is there a known problem with the `setup.py` or any dependencies in this branch that I should be aware of?

**Comment by probberechts** [comment]
Simply running the following works for me:

```sh
pip install git+https://github.com/probberechts/soccerdata.git@fix/whoscored-schedule
```

You could also try to install it using poetry.

**Comment by adlihs** [comment]
@probberechts is this problem fix? Im still face the same issue with the read_schedule() function, thanks in advance
