### ISSUE TITLE
No unique player identifier

### ISSUE THREAD

**Issue by ProjectPear100** [probberechts/soccerdata#597]
Is there any way we can join player data from multiple sources (FBref, WhoScored, SoFIFA) using an identifier or unique key of some sort? I have gone through the documentation and was unable to find any method to identify a unique player. Joining on names wont work since multiple players could have same names and also they are spelled differently across sources.

**Comment by probberechts** [comment]
You'll have to programatically and/or manually map the player ids between different data sources. There are no shortcuts and  soccerdata does not provide any support for doing this. In the future, I consider adding support for replacing player names / IDs by a standardized name / ID *given* a mapping (similarly to what is already possible for teams using the `config/teamname_replacements.json` file). But I consider creating the mapping itself out of scope for this package. 

For some tips on how to match player IDs across multiple data sources, I can recommend this blog post: https://unravelsports.github.io/2022/07/11/player-id-matching-system.html
