### ISSUE TITLE
[WhoScored] Sorry, you have been blocked You are unable to access whoscored.com | Cloudflare

### ISSUE THREAD

**Issue by pranavm28** [probberechts/soccerdata#603]
Getting blocked by WhoScored from scraping data. Was working fine less than 24 hrs ago. Issue came up for the first time like 14 hrs ago.

Any possible fix to this? Thanks!

**Comment by probberechts** [comment]
The scraper still seems to work fine for me. However, WhoScored has some very strong protection against scraping. Likely, you will eventually get blocked if you scrape large amounts of data in a short amount of time. To avoid this, you can use a proxy server as [explained in the docs](https://soccerdata.readthedocs.io/en/latest/reference/whoscored.html). Note that using tor won't work well though for WhoScored. It is easily detected.
