### ISSUE TITLE
[WhoScored] Adding European Championship as custom league

### ISSUE THREAD

**Issue by yureed** [probberechts/soccerdata#614]
Hello,
      I tried adding a custom league for Euros. According to the JS Console, the competition is called 'International-European-Championship'. I added the custom league like the following:

```json
{
  "INT-Euros": {
    "WhoScored": "International-European-Championship"

  }
}
```

The code also tells me that league_dict.json is loaded.
Then I got the following error:
![image](https://github.com/probberechts/soccerdata/assets/41127970/92188fe9-1acc-4b42-b0e0-26a429c275df)

**Comment by probberechts** [comment]
The correct league name is "International - European Championship" (note the spaces and hyphens). Also, note that the EUROs were added to the default supported leagues in version 1.8. See the [release notes](https://github.com/probberechts/soccerdata/releases/tag/v1.8.0) for details.

**Comment by yureed** [comment]
I wasn't aware it was in the default supported leagues. Forgot to check release notes. It works now. Thank you so much for your help!!
