### ISSUE TITLE
Not able to install soccerdata package

### ISSUE THREAD

**Issue by AbinThomas10** [probberechts/soccerdata#623]
![Screenshot 2024-06-30 041952](https://github.com/probberechts/soccerdata/assets/138511442/bea60302-a5bf-4108-98a0-cea7540196a2)

i already had the package but for some reason it showed a 500 Internal Server Error so i tried reinstalling Anaconda since then im not able to install the package

**Comment by probberechts** [comment]
I think this means that either your DNS system is not working correctly, or you have to use a proxy on your network and it isn't defined correctly. Anyway, this doesn't seem related to soccerdata (you'll probably have the same problem for any other package) so I'll close this. For instance StackOverlfow might be a better place to find help.
