### ISSUE TITLE
[FBref] Cannot call read_schedule() for upcoming 2024-2025 season data. Defaults to 1924-1925.

### ISSUE THREAD

**Issue by ds-oliver** [probberechts/soccerdata#658]
I would like to start pulling in schedule for upcoming season.

**Comment by probberechts** [comment]
I assume this is about FBref? It should work, but you have to retrieve the seasons again with caching disabled. Otherwise, it cannot know that the 2024/25 season exists.

```python
import soccerdata as sd
fbref = sd.FBref("ENG-Premier League", 2425, no_cache=True)
fbref.read_seasons()
```
