### ISSUE TITLE
Feature Request: Assists, Key Passes, Yellow Cards, Red cards info in understat.read_player_match_stats()

### ISSUE THREAD

**Issue by babu-akhil** [probberechts/soccerdata#661]
Is there any reason why these columns are not included? I needed them and was able to add them for my requirement. If you think this is a good change to have to the library, I'd like to contribute this small change through a PR. 

Thanks!

**Comment by probberechts** [comment]
Yes, it would be great if you could create a PR for this.

**Comment by babu-akhil** [comment]
Question: Do I need to run the nox test suite for all the python versions, i.e. for 3.8 -> 3.11 ? I am currently using 3.9 in my environment

**Comment by probberechts** [comment]
If you create a PR, it will automatically run the tests for all Python versions. No need to install all of them locally.

**Comment by babu-akhil** [comment]
Closing issue as feature merged
