### ISSUE TITLE
[FBref] requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url

### ISSUE THREAD

**Issue by URRealHero** [probberechts/soccerdata#668]
`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url`
This error occurs when I'm trying to scrape team_match_stats and player_match_stats.
What should I do to avoid this

**Comment by probberechts** [comment]
It looks like FBref has increased rate limiting from twenty to ten requests per minute recently (see https://www.sports-reference.com/bot-traffic.html).

You can increase the wait between requests as such:

```python
import soccerdata as sd

fbref = sd.FBref("ESP-La Liga", "23-24")
fbref.rate_limit = 6   # max 1 request per 6 seconds
```

I will update the default.

**Comment by mhd0528** [comment]
The fix works! And just a suggestion when using the fbref class, if you need to scrape from multiple pages/leagues, try to initialize or check league schedule as less as you can. All the calls will first go to [comps](https://fbref.com/en/comps/), which is usually the cause of the rate limit issue.

**Comment by URRealHero** [comment]
THXXXXXX A Lot~
