### ISSUE TITLE
[DOCS] Ambiguous team_dict.json and teamname_replacements.json usage

### ISSUE THREAD

**Issue by goosethedev** [probberechts/soccerdata#672]
In the Uniform team names section at the [Getting Started page](https://soccerdata.readthedocs.io/en/latest/intro.html#uniform-team-names), it is said to use `team_dict.json` to remap team names globally, but the library asks for a file named `teamname_replacements.json` when instantiating a scraper class.

Soccerdata ver.: `1.8.1`

**Comment by probberechts** [comment]
Thanks!
