### ISSUE TITLE
[FBref] Wrong year for player data 

### ISSUE THREAD

**Issue by AZA-2003** [probberechts/soccerdata#687]
Hello, 

it seems like read_player_season_stats() returns the 24-25 player stats  when 23-24 is passed as an argument; this seems to be happening with ITA-Serie A (I tried GER-Bundesliga and it worked fine)

**Comment by probberechts** [comment]
FBref or Understat? Can you provide a minimal code example?

**Comment by AZA-2003** [comment]
FBref and here is a code section
<img width="572" alt="image" src="https://github.com/user-attachments/assets/912a825f-76fb-4564-9a5c-246577819afe">

Thank you!

**Comment by probberechts** [comment]
This seems to work fine:

```python
>>> import soccerdata as sd

>>> fbref = sd.FBref("ITA-Serie A", "23-24", no_cache=True)
>>> df = fbref.read_player_season_stats(stat_type="standard")

>>> df.loc[("ITA-Serie A", "2324", "Atalanta", "Charles De Ketelaere"), "Performance"]

Gls      10
Ast       8
G+A      18
G-PK      9
PK        1
PKatt     1
CrdY      1
CrdR      0
Name: (ITA-Serie A, 2324, Atalanta, Charles De Ketelaere), dtype: Int64
```

De Ketelaere scored 10 goals last season, so this is correct!

**Comment by AZA-2003** [comment]
Oh it works now! Thank you so much for your time! I really appreciate it!
