### ISSUE TITLE
FBRef against stats

### ISSUE THREAD

**Issue by RobiFera** [probberechts/soccerdata#78]
Hi! First of all, thank you for the code!

I'd like to ask if it would be possible to also get stats from the "Opponent Stats" table,
Thanks!

**Comment by probberechts** [comment]
I am not sure to which table you are referring. Can you provide a link?

**Comment by RobiFera** [comment]
yep, so for example when viewing the league stats and scrolling down to the various team stats tables, there is an option to switch to an "Opponent Stats" table.

https://fbref.com/en/comps/11/Serie-A-Stats

![Capture](https://user-images.githubusercontent.com/31993778/186987299-bd1accb4-1760-4045-bee4-9c22a515b445.JPG)

**Comment by probberechts** [comment]
No, that is currently not implemented. It is a good suggestion, though! I will probably add it at some point, but it might take a while until I find the time time to do so. Feel free to implement it yourself and create a PR.

**Comment by RobiFera** [comment]
Those are the lines where I changed "_for" to "_against"

https://github.com/probberechts/soccerdata/blob/50f6fef099761a9fca692dbebb96459fba8b393b/soccerdata/fbref.py#L193
https://github.com/probberechts/soccerdata/blob/50f6fef099761a9fca692dbebb96459fba8b393b/soccerdata/fbref.py#L196

Note that, from what I've seen, only teams have that "Opponent Stats" table

**Comment by mhd0528** [comment]
Hi, is getting opponent team info from `read_team_match_stats `still supported? I got the following error. Any suggestions how to fix this? Thanks in advance!
```
File "/home/anaconda3/envs/soccerdata/lib/python3.10/site-packages/soccerdata/fbref.py", line 432, in read_team_match_stats
    (html_table,) = tree.xpath(f"//table[@id='matchlogs_{opp_type}']")
ValueError: not enough values to unpack (expected 1, got 0)
```
