### ISSUE TITLE
Tor port is not up to date

### ISSUE THREAD

**Issue by david-leconte** [probberechts/soccerdata#83]
(seen on Windows 11)

The Tor port specified in the code for when initializing a scraper with the `proxy="tor"` option is 9050, whereas the new Tor versions seem to use port 9150.

Something should be done to check whether port 9050 works in the first place and if it doesn't check with 9150.

For other people it doesn't work for right now, you can always do this :

```
return_proxies = lambda: {
    "http": "socks5://127.0.0.1:9150",
    "https": "socks5://127.0.0.1:9150",
}

ws = sd.WhoScored(leagues="ENG-Premier League", seasons=20-21, proxy=return_proxies)
```

**Comment by probberechts** [comment]
I've just updated Tor and it still defaults to port 9050. Did you perhaps install the Tor Browser Bundle? That distribution indeed defaults to listening on port 9150.

**Comment by probberechts** [comment]
Anyway, thanks for raising the issue. I think it would be good to add this to the docs.

**Comment by david-leconte** [comment]
The only difference from a regular installation was that I downloaded the
Tor files and executable from a German mirror due to DNS blocking, maybe
that's what it is.

No problem, thanks for adressing the issue!
